### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by hadnet** [TechInSite/vite-plugin-shim-react-pdf#4]
After install this package I'm getting this error:
       
    Uncaught ReferenceError: global is not defined
    at node_modules/vite-compatible-readable-stream/lib/_stream_readable.js (_stream_readable.js:46:21)
    at __require2 (chunk-T5W7KHNC.js?v=17605442:36:44)
    at node_modules/vite-compatible-readable-stream/readable-browser.js (readable-browser.js:3:1)
    at __require2 (chunk-T5W7KHNC.js?v=17605442:36:44)
    at node_modules/blob-stream/index.js (index.js:1:22)
    at __require2 (chunk-T5W7KHNC.js?v=17605442:36:44)
    at asyncToGenerator.js:32:13

I'm using Vite 2.7.2. Can you help me to sole this issue?

**Comment by thekevinbrown** [comment]
Could you provide an example repo that reproduces the problem so I can have a closer look?

**Comment by hadnet** [comment]
I just figured it out. I was using the pluginRewriteAll() at the end of the plugins array and that was causing the error. Using like this works: 
```json
{
 ...
 plugins: [react(), pluginRewriteAll(), shimReactPdf()],
 ...
}
```

**Comment by thekevinbrown** [comment]
Ah, glad you managed to fix it, thanks for reporting back!
