### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by vctqs1** [TechInSite/vite-plugin-shim-react-pdf#5]
I got this error when I yarn add new packages, have to remove `node_modules` and install whole packages at onces, quite noisy for me 
```
Uncaught ReferenceError: process is not defined
    at node_modules/util/util.js (util.js:109:1)
    at __require2 (chunk-LRGSRDRI.js?v=ab1c3ce3:19:44)
    at node_modules/vite-compatible-readable-stream/lib/_stream_readable.js (_stream_readable.js:58:17)
    at __require2 (chunk-LRGSRDRI.js?v=ab1c3ce3:19:44)
    at node_modules/vite-compatible-readable-stream/readable-browser.js (readable-browser.js:3:1)
    at __require2 (chunk-LRGSRDRI.js?v=ab1c3ce3:19:44)
    at node_modules/blob-stream/index.js (index.js:1:22)
    at __require2 (chunk-LRGSRDRI.js?v=ab1c3ce3:19:44)
    at asyncToGenerator.js:32:13
```

Anyone encourages this iss? please helpp meeee :(

Version
```
 "vite-plugin-shim-react-pdf": "1.0.4",
```

**Comment by vctqs1** [comment]
Here is my config in vite.config
```
resolve: {
            dedupe: ["react", "react-dom"],
            alias: {
                "./variants/VITE_PJ_OWNER": `./variants/${currentEnvironments.VITE_PJ_OWNER}`,
            },
        },
```

I think it dont map with it https://github.com/exogee-technology/vite-plugin-shim-react-pdf/blob/main/src/index.js#L17

**Comment by vctqs1** [comment]
Changes to this help resolve
```
alias: [
                {
                    find: "./variants/VITE_PJ_OWNER",
                    replacement: `./variants/${currentEnvironments.VITE_PJ_OWNER}`,
                },
            ],
```
